name: 2nd Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello Woorld!"
      - name: Print goodbye
        run: echo "Done - bye"
      
